# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_7_Riyad Febrian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2Jq9r4KDc9hTvTbfaXv0Rcr2AZ3IOk3
"""

import tweepy, string, nltk, re
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

nltk.download("stopwords")
nltk.download('punkt')

# Declare API Key
consumer_key = "------CONSUMER API KEY------"        
consumer_secret = "------CONSUMER SECRET KEY------"

# Stemmer Object
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Configure Stopwords
stop_words =  set(stopwords.words('indonesian'))

def clean_tweets(tweet):
  # 1. Case Folding
  tweet = re.sub(r"http\S+", "", tweet) # Remove url
  tweet = re.sub(r"\d+", "", tweet) # Remove Numbers
  tweet = tweet.lower().strip() # remove trailing spaces & lowerize
  tweet = tweet.replace('\n\n', '') # Remove tweet line break

  # 2. Stemming
  tweet = stemmer.stem(tweet)

  # 3. Punctuation
  tweet = tweet.translate(str.maketrans("","",string.punctuation))

  # 4. Tokenization
  tokens = nltk.tokenize.word_tokenize(tweet)

  # 5. Remove Stop Words
  tweet = [w for w in tokens if not w in stop_words]

  return tweet

def get_tweet(count):
  all_tweets = []
  for status in tweepy.Cursor(api.user_timeline, id='jokowi', tweet_mode='extended').items(count):
    all_tweets.append(clean_tweets(status.full_text))
  
  return all_tweets

if __name__ == '__main__':
  # konfigurasi consumer_key, consumer_secret
  auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
  # authentication
  api = tweepy.API(auth)

  total = 200
  counter = 0

  # Scrape latest 200 tweets Pak Jokowi
  cleaned_tweets = get_tweet(total)

  # Counting tweets contain 'covid'
  for tweet in cleaned_tweets:
    if 'covid' in tweet:
      counter+=1
  
  print(f'Banyaknya tweet Pak Jokowi yang diambil: {total}')
  print(f'Banyaknya Pak Jokowi membicarakan Covid dalam tweetnya : {counter}')

