# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_10_Riyad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7TRQ2VEfl52n1IzqHFHYHbpUf9t1TjR
"""

import requests
import pandas as pd
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl import Workbook

response = requests.get('https://pokemondb.net/pokedex/all')
df = pd.read_html(response.content, flavor='bs4')

df = df[0][df[0]['#'] <= 12]

wb = Workbook()
ws = wb.active

for r in dataframe_to_rows(df, index=False, header=True):
    ws.append(r)

wb.save("TugasPythonLanjutan_Hari_10_Riyad.xlsx")