# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_4_Riyad Febrian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PE2c9jaQ0QEP7yAiB6RwjLl4KK79AVCW
"""

import pandas as pd
import requests

response = requests.get('https://pokemondb.net/pokedex/all')

if __name__ == '__main__':
  df = pd.read_html(response.content, flavor='bs4')

  pokedex_20 = df[0]['#'] <= 20
  pokemon = df[0][pokedex_20]

  pokemon.to_csv('pokemon.csv', index=False)

