# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_3_Riyad Febrian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJF66dRogYmZuiT3Je_-II9g2Gn09WJf
"""

import pandas as pd
import re

URL_1 = 'https://en.wikipedia.org/wiki/List_of_brightest_stars'
URL_2 = 'https://en.wikipedia.org/wiki/List_of_action_films_of_the_2020s'

def clean_data(df):
  # drop unnecessary column
  df.drop(['Unnamed: 5', 'Unnamed: 6'], axis=1, inplace=True)
  # drop first row
  df = df[1:].reset_index(drop=True)
  # fill null values
  df['Subgenre/notes'][df['Subgenre/notes'].isna()] = '-'
  return df

def rm_square_bracket(df):
  # remove [...] values
  df['Subgenre/notes'] = df['Subgenre/notes'].apply(lambda x: re.sub(r'\[.*.', '', x))
  return df


def tugas_one():
  """ ambil data dari https://en.wikipedia.org/wiki/List_of_brightest_stars 
  dan simpan menjadi dataframe """

  df = pd.read_html(URL_1, flavor='bs4')
  return df[0]

def tugas_two():
  """ ambil data dari https://en.wikipedia.org/wiki/List_of_action_films_of_the_2020s
  untuk tahun 2020 dan 2021 simpan menjadi list gabungan"""

  df = pd.read_html(URL_2, flavor='bs4')
  # Cleaning part
  data_2020 = rm_square_bracket(clean_data(df[1]))
  data_2021 = rm_square_bracket(clean_data(df[2]))

  return data_2020.values.tolist() + data_2021.values.tolist()

if __name__ == '__main__':
  print(f'{"No.1".center(80, "-")}')
  print(tugas_one())

  print(f'{"No.2".center(80, "-")} \n {tugas_two()}')

