# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_2_Riyad Febrian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ztvfbgrnWxPmegggras_kXR-1RpCGImQ
"""

import requests
from bs4 import BeautifulSoup

url = 'https://blog.sanbercode.com/'
response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')

area_scrape = soup.find_all('div', {'class' : 'row justify-content-center'})

for content in area_scrape:
  title = [a.text.strip() for a in content.find_all('h2', {'class' : 'mb-2 h6'})]
  author = [a.text.strip() for a in content.find_all('a', {'class' : 'text-muted text-capitalize'})]

title_author = [(title[x] + " ditulis oleh " + author[x]) for x in range(len(title))]
print(f'{chr(10).join(title_author)}')